#!/usr/bin/env bash
# Install system with current configuration and ChaoticNyx packages

SCRIPTPATH=$( cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

sudo nixos-install --flake ${SCRIPTPATH}/..#mirl\
	--option 'substituters' 'https://nixos-cache-proxy.cofob.dev'\
	--option 'extra-substituters' 'https://attic.xuyh0120.win/lantian https://install.determinate.systems https://noctalia.cachix.org'\
       	--option 'extra-trusted-public-keys' 'lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4='
