#!/usr/bin/env bash
# Install system with current configuration and ChaoticNyx packages

SCRIPTPATH=$( cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

sudo nixos-install --flake ${SCRIPTPATH}/..#mirl\
	--option 'substituters' 'https://nixos-cache-proxy.cofob.dev'\
	--option 'extra-substituters' 'https://attic.xuyh0120.win/lantian'\
       	--option extra-trusted-public-keys "lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc="
