#!/usr/bin/env bash
# Install system with current configuration and ChaoticNyx packages

SCRIPTPATH=$( cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

sudo nixos-install --flake ${SCRIPTPATH}/..#mirl\
	--option 'substituters' 'https://nixos-cache-proxy.cofob.dev'\
	--option 'extra-substituters' 'https://nyx-cache.chaotic.cx/ https://install.determinate.systems'\
       	--option 'extra-trusted-public-keys' 'nyx-cache.chaotic.cx:dJxTrgMC3V3cFfyIiBQDQorG6k1LsqurH/srpMSq7qk= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM='
